mod chapter_10;
mod chapter_11;
mod chapter_12;
mod chapter_13;
mod chapter_14;
mod chapter_15;
mod chapter_16;
mod chapter_17;
mod chapter_18;
mod chapter_19;
mod chapter_2;
mod chapter_3;
mod chapter_4;
mod chapter_5;
mod chapter_6;
mod chapter_7;
mod chapter_8;
mod chapter_9;
mod lib;

pub fn start_rust_book() {
    // chapter_2::run();
    // chapter_3::run();
    // chapter_4::run();
    // chapter_5::run();
    // chapter_6::run();
    // chapter_7::run();
    // chapter_8::run();
    // chapter_9::run();
    // chapter_10::run();
    // chapter_11::run();
    // chapter_12::run();
    // chapter_13::run();
    // chapter_14::run();
    // chapter_15::run();
    // chapter_16::run();
    // chapter_17::run();
    // chapter_18::run();
    chapter_19::run();
}
